### PR TITLE
Added basic TravisCI file

### PR DESCRIPTION
**Pull request by OmarIthawi**
Better than run the cookiecutter locally every time, let Travis do it.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-2604](https://openedx.atlassian.net/browse/OSPR-2604) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by OmarIthawi** [comment]
@mduboseedx Could you please get this activated? It's going to be useful as this repo is becoming a bit more complex (#4).

**Comment by mduboseedx** [comment]
@edx/platform-team Could you give this a look? Let me know if this should be assigned to a different team.

**Comment by doctoryes** [comment]
@OmarIthawi LGTM. Would you rather that Travis be activated for this PR pre-merge? What's your preference for order of operations?

**Comment by OmarIthawi** [comment]
Please do @doctoryes! I'd like to address failures if any.

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/cookiecutter-xblock&entry.867055334=https://github.com/edx/cookiecutter-xblock/pull/5&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2018-09-09+06:24&entry.1917517419=2018-09-13+15:57&entry.2133058324=No) so we can improve your experience in the future.

**Comment by jibsheet** [comment]
Closed and re-opened to trigger the travis build, sorry about the bot noise

**Comment by doctoryes** [comment]
@OmarIthawi Travis is enabled so the PR is testable and ready to be fixed.

**Comment by OmarIthawi** [comment]
Thanks @doctoryes and @jibsheet! The build is passing and the PR ready to be merged.

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/cookiecutter-xblock&entry.867055334=https://github.com/edx/cookiecutter-xblock/pull/5&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2018-09-09+06:24&entry.1917517419=2018-09-14+13:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
